chore(deps): Pin aws-sdk to v2.893.0
Fixes an error where, when using node-riffraff-artifact via npx the following error is seen:

```console
internal/modules/cjs/loader.js:883
08:06:27
      throw err;
08:06:27
      ^
08:06:27
    08:06:27
    Error: Cannot find module '/root/.npm/_npx/248/lib/node_modules/@guardian/node-riffraff-artifact/node_modules/aws-sdk/scripts/check-node-version.js'
08:06:27
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
08:06:27
        at Function.Module._load (internal/modules/cjs/loader.js:725:27)
08:06:27
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
08:06:27
        at internal/main/run_main_module.js:17:47 {
08:06:27
      code: 'MODULE_NOT_FOUND',
08:06:27
      requireStack: []
08:06:27
    }
08:06:27
    npm ERR! code ELIFECYCLE
08:06:27
    npm ERR! errno 1
08:06:27
    npm ERR! aws-sdk@2.897.0 postinstall: `node scripts/check-node-version.js`
08:06:27
    npm ERR! Exit status 1
08:06:27
    npm ERR!
08:06:27
    npm ERR! Failed at the aws-sdk@2.897.0 postinstall script.
08:06:27
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
08:06:27
    08:06:27
    npm ERR! A complete log of this run can be found in:
08:06:27
    npm ERR!     /root/.npm/_logs/2021-05-03T07_06_27_225Z-debug.log
08:06:27
    Install for [ '@guardian/node-riffraff-artifact@latest' ] failed with code 1
08:06:29
    Process exited with code 1
```

It looks like since v2.894.0 aws-sdk attempts to run `node scripts/check-node-version.js` on install
which fails.

Pinning this dependency to v2.893.0 exactly to overcome this issue.

See:
  - https://github.com/aws/aws-sdk-js/pull/3727